trigger:
  branches:
   include:
     - main
pool:   
 name: agent-classic

stages:
  - stage: test
    jobs:
      - job: infrapipeline
        steps:
        - task: TerraformInstaller@1
          displayName: terraform install
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
            backendServiceArm: 'amol-sc'
            backendAzureRmResourceGroupName: 'rgamak'
            backendAzureRmStorageAccountName: 'amakstg'
            backendAzureRmContainerName: 'amakcontainer'
            backendAzureRmKey: 'terraform.tfstate'
        - task: TerraformTask@5
          displayName: validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/infra'
   
 